openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
  description: API lấy danh sách người dùng
paths:
  /users:
    get:
      summary: Lấy danh sách người dùng
      tags:
        - Users
      responses:
        "200":
          description: Thành công
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: Nguyễn Văn A
                    email:
                      type: string
                      example: user@example.com
